algoritmo "Exercicio1"
// Função : Cálculo do Salário Família
// Autor : Enio Amarantes
// Data : 19/03/2018
// Seção de Declarações 
var
sal_fa, dep : real
inicio
// Seção de Comandos
escreval ("Qual é o seu salário base? ")
leia (sal_fa)
escreval ("Qual é a quantidade de dependentes da sua família? ")
leia (dep)
escreva ("Para ",dep ," pessoas seu salário família será de R$ " ,sal_fa * dep * 0.02,",00.")
escreval (" ")
fimalgoritmo
