algoritmo "Funcao05"
// Função :– Faça um algoritmo que crie uma função que receba um número inteiro como parâmetro e
// retorne 1, se sua raiz quadrada é exata, e 0 em caso contrário
// Autor : Enio Amarnte
// Data : 22/05/2018
// Seção de Declarações 
var
x : inteiro
  funcao raiz(a: inteiro) : inteiro
  var

  inicio
        se (raizq(x)
  fimfuncao
  
inicio
escreval ("Informe um valor")
leia (x)
escreval ("A função retornou", raiz(x))
fimalgoritmo
