algoritmo "Exercicio1"
// Função : Exibir sequência de números
// Autor : Enio Amarantes
// Data : 10/04/2018
// Seção de Declarações
// Faça um algoritmo que imprima todos os números inteiros de 1 a N (fornecido pelo usuário).
var
x, y : inteiro

inicio
// Seção de Comandos 
x <- 0
escreval ("Até que número deseja exibir: ")
leia (y)

para x de 0 ate y faca
     escreval (x)
     x <- (x+1)
fimpara
fimalgoritmo
