/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package relatorios;

import bancodados.JDBCUtil;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 * @author fabricio
 */
public class JanelaRelatorio extends javax.swing.JFrame {

    Connection con = null;

    public static final String relatorio01_pdf
            = System.getProperty("user.dir") + "/src/relatorios/Relatorio001.pdf";
    public static final String fonte_relatorio01
            = System.getProperty("user.dir") + "/src/relatorios/Relatorio001.jrxml";
    public static final String relatorio01
            = System.getProperty("user.dir") + "/src/relatorios/Relatorio001.jasper";
    public static final String relatorio_produto
            = System.getProperty("user.dir") + "/src/relatorios/produto.jasper";
 public static final String relatorio_vendas
            = System.getProperty("user.dir") + "/src/relatorios/vendas.jasper";
    /**
     * Creates new form JanelaCliente
     */
    public JanelaRelatorio() {
        JDBCUtil.init();
        con = JDBCUtil.getConnection();

        initComponents();

        System.out.println(System.getProperties());
    }

    private Map constroiParametrosProduto() {
        Map params = new HashMap();
        int codp = Integer.valueOf(
                JOptionPane.showInputDialog(
                        this,
                        "Digite o código do Produto",
                        "Entrada de dados",
                        JOptionPane.QUESTION_MESSAGE));
        params.put("idProduto", codp);
        return params;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Visualizar Relatório");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Gerar PDF do Relatório");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Relatório Produto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Relatório de Vendas por Região");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(70, 70, 70)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        JasperPrint impressao;
        try {
            // caso seja necessárioi, compila o relatório (caso deseja usar o jrxml)
            //JasperReport relatorio01 = JasperCompileManager.compileReport(fonte_relatorio01);

            //preenchimento do relatorio com a conexao e parametros
            impressao = JasperFillManager.fillReport(
                    relatorio01,
                    null,
                    con);

            //opcao de visualizar o relatorio
            JasperViewer.viewReport(impressao);

        } catch (JRException erro) {
            System.err.println("Não foi possível construir o relatório.\n\n" + erro);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JasperPrint impressao;
        try {
            // compila o relatório (caso deseja usar o jrxml)
            //JasperReport relatorio01 = JasperCompileManager.compileReport(fonte_relatorio01);

            //preenchimento do relatorio com a conexao e parametros
            impressao = JasperFillManager.fillReport(
                    relatorio01,
                    null,
                    con);

            //opcao de exportar o relatorio diretamente para arquivo
            JasperExportManager.exportReportToPdfFile(impressao, relatorio01_pdf);

            JOptionPane.showMessageDialog(this, "Gerado o arquivo com sucesso: " + relatorio01_pdf);
        } catch (JRException erro) {
            System.err.println("Não foi possível exportar o relatório.\n\n" + erro);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JasperPrint impressao;
        try {
            
            // compila o relatório (caso deseja usar o jrxml)
            //JasperReport relatorio_produto = JasperCompileManager.compileReport("arquivo .jrxml");
            
            impressao = JasperFillManager.fillReport(
                    relatorio_produto,//arquivo compilado ou .jasper ou o .jrxml compilado (veja acima)
                    constroiParametrosProduto(),
                    con);

            JasperViewer.viewReport(impressao);
        } catch (JRException erro) {
            System.err.println("Não foi possível visualizar o relatório.\n\n"+erro);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JasperPrint impressao;
        try {
            
            // compila o relatório (caso deseja usar o jrxml)
            //JasperReport relatorio_vendas = JasperCompileManager.compileReport("arquivo .jrxml");
            
            impressao = JasperFillManager.fillReport(
                    relatorio_vendas,//arquivo compilado ou .jasper ou o .jrxml compilado (veja acima)
                    null,//não há parâmetros
                    con);

            JasperViewer.viewReport(impressao);
        } catch (JRException erro) {
            System.err.println("Não foi possível visualizar o relatório.\n\n"+erro);
        }    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaRelatorio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaRelatorio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaRelatorio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaRelatorio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
